
/*
===========================================================
                 MOVIES DATA ANALYSIS
===========================================================

Database  : MySQL
Dataset   : Movies
Project   : SQL Data Analysis

DESCRIPTION:
This project focuses on analyzing movie data using SQL.
The dataset contains information about movies, directors,
stars, ratings, votes, and gross revenue.

OBJECTIVE:
The goal of this project is to use SQL to explore movie
performance, identify successful directors and stars, and
analyze highly rated and popular movies.

SQL CONCEPTS USED:
- SELECT
- GROUP BY
- ORDER BY
- Aggregate Functions
- WHERE
- Subqueries
- Common Table Expressions (CTEs)
- HAVING
- IN
- Filtering and Ranking

KEY ANALYSIS:
- Total gross revenue by director
- Top-performing directors
- Highly rated movies
- Popular movies based on votes
- Stars with high average movie ratings

===========================================================
*/
-- Q1) Display all records from the movies table.

SELECT * FROM movies;


-- Q2) What is the total gross revenue generated by each director,
-- and which directors have generated the highest total revenue?

USE data3;
SELECT director,SUM(gross) FROM data3.movies
GROUP BY  director
ORDER BY SUM(gross) DESC;


-- Q3) What are the movies directed by the top 3 directors based on
-- their total gross revenue?

WITH top_dir AS (SELECT director
					  FROM movies
					  GROUP BY  director
                      ORDER BY SUM(gross) 
					  DESC LIMIT 3)
SELECT * FROM movies
WHERE director IN (SELECT * FROM top_dir);


-- Q4) Which movies have more than 25,000 votes and a score above 8.5,
-- ordered by score and votes?

SELECT * FROM data3.movies
WHERE name IN (SELECT * FROM data3.movies
                    WHERE votes >25000 AND score >8.5
                    ORDER BY score DESC , votes DESC);


-- Q5) Which stars have an average movie score above 8.5 among movies
-- with more than 25,000 votes, and what are all the movies featuring them?

WITH sstars AS  (SELECT star FROM movies
                WHERE votes > 25000
                GROUP BY star HAVING AVG(score) > 8.5)
SELECT * FROM movies
WHERE star IN (SELECT * FROM sstars);
